= Java IO

=== task 1

Реализация решения лежит в двух методах класса FileUtil. copyContent - в методе происходит выбор из какого файла в
какой происходит перезапись. Метод copyContentWithUpperCase -описывает основную логику перезаписи.

=== task 2

Реализовать метод, который принимает путь к файлу. Метод возвращает список строк этого файла. Для решения задачи был
создан метод stringList, который построково считывает информацию в файле и сохраняет их в коллекции List/

=== task 3

Реализовать метод, который принимает путь к файлу. Метод возвращает список слов начинающихся с гласной буквы. Для решения
создан метод wordsFromVowelLetter, который проверяет слова из строчек файла на совпадение с гласными буквами англ и рус
алфавита, после их отлова записывает их в коллекцию

=== task 4

Реализовать метод, который принимает путь к файлу. Метод возвращает список слов, для которых последняя буква совпадает
с первой буквой следующего за ним слова. Сохраняется примерная логика из прошлого таска, однако в методе
wordsWithLastMatches так же происходит проверка по равенству последнего чара предыдущего слова и первого чара текущего.

=== task 5

Реализовать метод, который принимает путь к файлу. Метод возвращает список наибольшей комбинации цифр для каждой
строки, которые идут в порядке возрастания. Реализация поставленной задачи решена с применением двух методов:
-findListOfLargestNumberCombination - который проверяет содержимое строк на наличие последовательности и сохраняет
эти последовательности во временном хранилище;
-getListOfLargestNumberCombination -метод сплитит стоки файла и вызывает метод финд, в результате чего забирает
наибольшую последовательность.

=== task 6

Реализовать метод, который принимает путь к файлу. Метод возвращает частоту повторяемости всех букв в тексте,
игнорируя регистр.
Для решения таска написан метод getFrequencyRepetitionAllLettersText, в котором происходит запись в коллекцию  Мар чаров
после чего проверка вхождения данного чара в коллекцию и при положительной проверке добавление количества

=== task 7

Реализовать метод, который принимает путь к файлу. Метод возвращает частоту повторяемости всех слов в тексте в
порядке возрастания частоты повторяемости.
Решение реализованно в методе getFrequencyAllWords, в котором происходит поиск уникальных слов и запись количества
их повторений. Добавлен кастомный компаратор  CustomComparator, в котором прописанна логика сортировки коллекции
в зависимости от значения(значением является количество повторений слов)

=== task 8

Реализовать метод, который принимает путь к файлу с целыми числами и сортирующий содержимое файла по возрастанию и
сохраняющий результат в файл ${origin_filepath}_.
Для решения написан метод sortedInFile, в котором происходит чтение данных из файла с записью в массив, далее при помощи
метода Arrays.sort - происходит натуральная сортировка значений массива с последующей записьбю в новый фаил

=== task 9

Реализовать метод, который принимает путь к файлу, где содержится фамилия студентов и их оценки
(в качестве разделителя используется ,) и возвращает успеваемость студентов.
Реализация решения в методе averageScore, в котором происходит построковое чтение файла с последующим нахождением чисел
в строке, после чего нахождения всех чисел входящих в строку находится их среднее значение

=== task 10

еализовать метод, который принимает путь к файлу с java кодом, и 2 модификатора доступа в виде строки и заменяет все
модификаторы доступа X в объявлении атрибутов и методов класса на Y и сохраняющий результат в файл ${origin_filepath}_.
Для решения таска использована логика таска 1. replaiceModification - метод в котором описана логика замены.
javaReplaiceModificator - выбор направления замены.