= Concurrent utilities

NOTE: При выполнении заданий использовать не нативные инструменты Java, а инструменты из пакета `java.util.concurrent`

== Project 'Improved Parallel Calculator'

TIP: Если есть некоторое количество однотипных задач, то их следует выполнять параллельно. При этом возникает необходимость управления параллельным выполнением этих задач и сохранения их результата.

=== Specification of task 1

Реализовать метод:

* принимающий список массивов, состоящий из случайных целых чисел (от 1 до 300) случайной длины (до 1 млн элементов)
* возвращающий массивы и сумму элементов в них

=== Specification of task 2

Реализовать метод, аналогичный предыдущему, но принимающий количество потоков, в которых будет происходить выполнение.

=== Specification of task 3

Сравнить затраченное на выполнение время для списка массивов размерностью `10` для:

* метода работающего в 1 потоке
* метода работающего в 2 потоках
* метода работающего в 5 потоках
* метода работающего в 10 потоках


= Concurrency. Thread synchronization.

TIP: Когда нескольким потокам необходимо работать с одними и теми же данными, то создается _общий ресурс_, доступ к которому имеют все эти потоки.

TIP: Не использовать поток `main`, как поток, который выполняет какую-то задачу/работу. Чаще всего поток `main` является _координирующим_ потоком, т.е. потоком где создаются другие потоки, общие ресурсы для этих потоков и т.д.

TIP: Необходимо корректно выделить задачу/работу, которую можно выполнить в отдельном потоке.

== Project `Producer-Consumer`

WARNING: Обязательное требование: корректная работа в многопоточной среде.


=== Specification of task 1

Создать класс `Store` представляющий собой хранилище целых чисел.

=== Specification of task 2

Добавить в класс `Store` метод `produce()`, который принимает и добавляет в хранилище простое число. Максимальное количество чисел, которое может содержать в `Store` равно `10`.

=== Specification of task 3

Добавить в класс `Store` метод `consume()`, который забирает из `Store` (т.е. число удаляется из него).

=== Specification of task 4

Создать и запустить несколько потоков `ProducerThread`, которые производят числа для `Store`.

=== Specification of task 5

Создать и запустить несколько потоков `ConsumerThread`, которые потребляют числа из `Store`.

=== Specification of task 6

Добавить логирование (в виде вывода в *Standard Output* или файл) всех ключевых этапов работы потоков.
